title: Reifion
description: Brilian Putra Amiruddin's Personal Website
author: Brilian Putra Amiruddin
avatar: /me.jpg
email: brilianpamiruddin@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
disqus: kaienknight

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: brilianputraa
  card: summary
logo: logo.png
social:
  name: Brilian Putra Amiruddin
  links:
    - https://twitter.com/brilianputraa
    - https://github.com/brilianputraa
    - https://scholar.google.com/citations?user=z1moK68AAAAJ&hl=en
    - https://brilianputraa.medium.com/
google_site_verification: #
lang: en
